sudo: required
services:
  - docker

before_install:
  - docker build -t mawglih/amu -f Dockerfile.dev .

script:
  - docker run mawglih/amu npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "alphmarineupholstery"
  env: "Alphamarineupholstery-env"
  bucket_name: "elasticbeanstalk-us-east-2-202717464391"
  bucket_path: "alphmarineupholstery"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY